name: 'KubeVela website sync'
branding:
  icon: "cloud-lightning"
  color: "blue"
description: 'Automatically sync documents to KubeVela website.'
author: 'wonderflow'
inputs: 
  gh-page:
    description: 'github page repo'
    required: true
  docs-path:
    description: 'path of docs dir'
    required: true
    default: 'docs'
  branch:
    description: 'branch for the push target repo'
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh-page }}
    - ${{ inputs.docs-path }}
    - ${{ inputs.branch }}
